describe("require('libdash_nvim')", function()
  it("should be able to require('libdash_nvim')", function()
    local ok, libdash = pcall(require, 'libdash_nvim')
    assert.is_true(ok)
    assert.is_true(libdash ~= nil)
    assert.is_true(libdash.query ~= nil)
    assert.are.equal('function', type(libdash.query))
  end)
end)
