name: Run All Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-lua:
    name: Run Luacheck and Stylua
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.5.1
    - name: Setup 'lua'
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"
    - name: Setup 'luarocks'
      uses: leafo/gh-actions-luarocks@v4
    - name: Run Luacheck
      run: |
        luarocks install luacheck
        luacheck .
    - name: Run Stylua
      uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .
        version: 0.10.1

  check-rust:
    name: Build Rust and Lint with Clippy
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Rust
        run: make build-macos-x86
      - name: Lint Rust
        run: make lint-rust

  check-integration:
    name: Run Lua Integration Tests
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run All Tests
        run: make test
